- name: Create data dir for prometheus
  file:
    path: /opt/prometheus
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0755"

- name: Copy jmx_prometheus_javaagent-0.12.0.jar
  copy:
    src: ../files/prometheus/jmx_prometheus_javaagent-0.12.0.jar
    dest: /opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0644"

- name: Copy zookeeper.yml
  copy:
    src: ../files/prometheus/zookeeper.yml
    dest: /opt/prometheus/zookeeper.yml
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0644"

- name: Copy kafka-2_0_0.yml
  copy:
    src: ../files/prometheus/kafka-2_0_0.yml
    dest: /opt/prometheus/kafka-2_0_0.yml
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0644"
