- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Make sure that Zookeeper is running
  systemd:
    state: started
    name: zookeeper

- name: Wait Zookeeper start
  wait_for:
    timeout: 10

- name: Make sure that Kafka is running
  systemd:
    state: started
    name: kafka
